In [10]:
import pandas as pd


stocks = {
    'PLW': 387.00,
    'CDR': 339.5,
    'TEN': 349.5,
    '11B': 391.0,
    'BBT': 25.5,
    'F51': 19.2,
}
quotations = pd.Series(data=stocks)


df = quotations.reset_index()
df.columns = ['ticker','price']

df

  ticker  price
0    PLW  387.0
1    CDR  339.5
2    TEN  349.5
3    11B  391.0
4    BBT   25.5
5    F51   19.2

In [16]:
import pandas as pd

dict_1 = {
    'company':["Amazone","Microsoft","Facebook"],
    'price':[2375.0,178.6,179.2],
    'ticker':['AMZN.US','MSFT.US','FB.US']
}


companies = pd.DataFrame(data=dict_1)

companies.set_index('company')

            price   ticker
company
Amazone    2375.0  AMZN.US
Microsoft   178.6  MSFT.US
Facebook    179.2    FB.US