1. **I love sunny days outside.** (Positive)

2. **This movie was really terrible.** (Negative)

3. **The concert was absolutely amazing tonight.** (Positive)

In [25]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [27]:
List_1 = ["I love sunny days outside","This movie was really terrible","The concert was absolutely amazing tonight"]
List_2 = [1,0,1]

In [29]:
df = pd.DataFrame({'Text': [text for text in List_1], 'Output': List_2})

In [31]:
df

                                         Text  Output
0                   I love sunny days outside       1
1              This movie was really terrible       0
2  The concert was absolutely amazing tonight       1

In [38]:
# Define stop words
stop_words = set(stopwords.words('english'))

In [40]:
# Function to remove stop words
def remove_stop_words(text):
    words = word_tokenize(text)  # Tokenize the text
    filtered_words = [word for word in words if word.lower() not in stop_words]  # Filter out stop words
    return ' '.join(filtered_words)  # Join words back into a string

In [42]:
# Apply the function to the 'text' column
df2['Text'] = df2['Text'].apply(remove_stop_words)

In [44]:
df2

                                 Text  Output
0             love sunny days outside       1
1               movie really terrible       0
2  concert absolutely amazing tonight       1

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
TfidfV = TfidfVectorizer(max_features=50,ngram_range=(1,1))

In [70]:
X = TfidfV.fit_transform(df2['Text']).toarray()

In [72]:
TfidfV.vocabulary_

{'love': 4,
 'sunny': 8,
 'days': 3,
 'outside': 6,
 'movie': 5,
 'really': 7,
 'terrible': 9,
 'concert': 2,
 'absolutely': 0,
 'amazing': 1,
 'tonight': 10}